# Generated by Django 4.2.4 on 2024-03-04 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParticipantConversation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('participant_id', models.CharField(max_length=100, unique=True)),
                ('chatbot_type', models.CharField(choices=[('Helpful', 'Group A - Helpful Chatbot'), ('Neutral', 'Group B - Neutral Chatbot')], max_length=50)),
                ('chatbot_conversation', models.JSONField()),
                ('chatbot_started_at', models.DateTimeField(blank=True, null=True)),
                ('chatbot_finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='participant',
            name='user',
        ),
        migrations.DeleteModel(
            name='ChatMessage',
        ),
        migrations.DeleteModel(
            name='Participant',
        ),
    ]
