name: "Continuous Deployment"

on:
  push:
    branches: ["main"]
jobs:
  deploy_production:
    runs-on: "ubuntu-22.04"
    env:
      RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
      DOMAIN: "chatty.c3l.ai"
      SSH_KEY_FILE: "/tmp/key.pem"
      DEPLOY_BRANCH: "main"
      SSH_KEY: ${{ secrets.SSH_KEY_PRODUCTION }}
    steps:
      - name: "Checkout code"
        uses: "actions/checkout@v4"

      - name: "Setup SSH key"
        run: |
          echo "$SSH_KEY" > $SSH_KEY_FILE
          chmod 400 $SSH_KEY_FILE
      - name: "Deploy"
        run: |
          ./deployment/deploy.sh
