name: "Continuous Deployment"

on:
  push:
    branches: ["main"]
jobs:
  deploy_production:
    runs-on: "ubuntu-22.04"
    env:
      DJANGO_SUPERUSER_USERNAME: "lab.manager"
      DJANGO_SUPERUSER_EMAIL: "lab.manager@c3l.ai"
      DJANGO_SUPERUSER_PASSWORD: {{ secrets.DJANGO_SUPERUSER_PASSWORD }}
      DJANGO_SECRET_KEY: {{ secrets.DJANGO_SECRET_KEY }}
      DJANGO_SETTINGS_MODULE: "anxiety_chatbot_project.settings-production"
      DOMAIN: "chatty.c3l.ai"
      SSH_KEY_FILE: "/tmp/key.pem"
      DEPLOY_BRANCH: "main"
      PRODUCTION_SSH_KEY: {{ secrets.PRODUCTION_SSH_KEY }}
    steps:
      - name: "Checkout code"
        uses: "actions/checkout@v4"

      - name: "Setup SSH key"
        run: |
          # Get secret from {{ secrets.PRODUCTION_SSH_KEY }} and put it in the SSH_KEY_FILE
          printenv PRODUCTION_SSH_KEY > $SSH_KEY_FILE
          chmod 400 $SSH_KEY_FILE
      - name: "Deploy"
        run: |
          ./deployment/deploy.sh
