name: "Continuous Integration"

on:
  push:
    branches: ["dev"]
jobs:
  deploy_uat:
    runs-on: "ubuntu-22.04"
    env:
      DJANGO_SUPERUSER_USERNAME: "lab.manager"
      DJANGO_SUPERUSER_EMAIL: "lab.manager@c3l.ai"
      DJANGO_SUPERUSER_PASSWORD: ${{ secrets.DJANGO_SUPERUSER_PASSWORD }}
      DJANGO_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY_UAT }}
      DJANGO_SETTINGS_MODULE: "anxiety_chatbot_project.settings-uat"
      DOMAIN: "chatty-uat.c3l.ai"
      SSH_KEY_FILE: "/tmp/key.pem"
      DEPLOY_BRANCH: "dev"
      SSH_KEY: ${{ secrets.SSH_KEY_UAT }}
    steps:
      - name: "Checkout code"
        uses: "actions/checkout@v4"

      - name: "Setup SSH key"
        run: |
          echo "$SSH_KEY" > $SSH_KEY_FILE
          chmod 400 $SSH_KEY_FILE
      - name: "Deploy"
        run: |
          ./deployment/deploy.sh
